---
apiVersion: v1
kind: Pod
metadata:
  generateName: jjb-
  labels:
    some-label: jenkins-job-builder
spec:
  containers:
    - name: jenkins-job-builder
      image: widerplan/jenkins-job-builder:v2.1.0
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /etc/jenkins_jobs/jenkins_jobs.ini
          name: jjb-config
          subPath: jenkins_jobs.ini
    - name: python
      image: python:alpine
      command:
        - cat
      tty: true
  nodeSelector:
    disktype: ssd
  volumes:
    - name: jjb-config
      configMap:
        name: jjb-config
